version: "3.1"

services:
  db:
    image: postgres:9.6
    command: postgres
    restart: "always"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: asclepias
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.7
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - discovery.zen.minimum_master_nodes=1
      - action.auto_create_index=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.7
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTICSEARCH_USERNAME=kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']

volumes:
  esdata:
